### ISSUE TITLE
Rule: `prefer-scope-imports`

### ISSUE THREAD

**Issue by sergeysova** [effector/eslint-plugin#110]
It is useful when writing an SSR application, but IDE is auto imported from `effector-react` or the same for `effector-solid`.

Fail:

```ts
// prefer-scope-imports: 'error'

import { useUnit, useList } from 'effector-react';
```

Okay:

```ts
// prefer-scope-imports: 'error'

import { useUnit, useList } from 'effector-react/scope';
```

I think the rule should be auto-fixable.

The rule should support configuring ecosystem packages:

```json
"effector/prefer-scope-imports": ["error", {
  "packages": ["@effector/reflect", "farfetched", "another-lib"],
},
```

Each this import should be located and replaced with an import `/scope` suffix.

This rule for the `scope` preset.

**Comment by igorkamyshev** [comment]
I believe, this issue has become obsolete since Effector 23 release. `/scope` imports are deprecated and will be deleted in the next major release.
