### ISSUE TITLE
Rule: `no-patronum-debug`

### ISSUE THREAD

**Issue by sergeysova** [effector/eslint-plugin#112]
I think this rule can help users to remove forgotten `debug` from production code.

Looks like this rule should be auto-fixable.

**Comment by raidenmiro** [comment]
>  Looks like this rule should be auto-fixable.

Hi, this fix supposed to remove the line with `debug` and import? Or just `debug` without import? 🤔

**Comment by sergeysova** [comment]
I think the rule should remove an import too.
