### ISSUE TITLE
TypeError with patronum rule

### ISSUE THREAD

**Issue by xsfunc** [effector/eslint-plugin#127]
`TypeError` occurred when linting this line:

```js
const Anchor = styled('a')({})
```

> at CallExpression (/rules/no-patronum-debug/[no-patronum-debug.js:34:73](https://github.com/effector/eslint-plugin/blob/0c7613351994f11245508f8715bf20232c9ec5e5/rules/no-patronum-debug/no-patronum-debug.js#L34))

Seems need `?` after `object` at 34 line.

**Comment by igorkamyshev** [comment]
Thanks for report, fixed in https://github.com/effector/eslint-plugin/releases/tag/v0.10.2
