### ISSUE TITLE
TypeError with `enforce-store-naming-convention`

### ISSUE THREAD

**Issue by xsfunc** [effector/eslint-plugin#128]
```js
function toStore(value) {
  return is.store(value) ? value : createStore(value)
} 
```

> TypeError: Cannot read properties of null (reading 'type')
in [enforce-store-naming-convention.js:153:24](https://github.com/effector/eslint-plugin/blob/f2348dfb2e2fd8db6bfdbaef855a4e2d6e82f907/rules/enforce-store-naming-convention/enforce-store-naming-convention.js#L153)

**Comment by igorkamyshev** [comment]
Thanks for report, fixed in 0.10.3
