### ISSUE TITLE
Store with name `$` (rule `enforce-store-naming-convention`)

### ISSUE THREAD

**Issue by yumauri** [effector/eslint-plugin#139]
This code
```js
const $ = createStore(0)
```
raises an error
```
Store "$" should be named with prefix, rename it to "$"
```

I'm not sure, should this name be an error, or no (but I think it should not, though), but error message is confusing :)

**Comment by igorkamyshev** [comment]
Interesting edge-case 🤗 I am pretty certain that it is almost impossible in the real application, so I assume we can do it as a “nice-to-have”, but it is deftly not a priority for me right now 🥲

So, feel free to handle this edge-case with a fancy error-message and send your PR 🙏
