### ISSUE TITLE
Convention of a store naming

### ISSUE THREAD

**Issue by egorguscha** [effector/eslint-plugin#31]
I would like to propose one more idea for naming with postfix $
`const store$ = createStore(null)`

**Comment by ilyaryabchinski** [comment]
Is anybody working on this one already? I'd like to take it 🙂

**Comment by igorkamyshev** [comment]
You are welcome to send your PR 😇

**Comment by ilyaryabchinski** [comment]
Sorry for the delay, I am gonna finalize and sumbit a PR later today 🏃‍♂️
