### ISSUE TITLE
no-ambiguity-target: ложные срабатывания в фабриках

### ISSUE THREAD

**Issue by sezyara** [effector/eslint-plugin#49]
В фабриках на effector имеются ложные срабатывания правила `effector/no-ambiguity-target` на `guard`.

Что говорит eslint:
`Method 'guard' returns 'target' and assigns the result to a variable. Consider removing one of them  effector/no-ambiguity-target`

Версии пакетов:
effector: 21.8.12
eslint: 7.32.0
eslint-plugin-effector: 0.3.0

Конфиг eslint:
```
module.exports = {
  root: true,
  extends: [
    'plugin:effector/recommended'
  ],
  parser: '@typescript-eslint/parser',
  plugins: [
    'effector',
    '@typescript-eslint'
  ]
}
```

Пример кода: [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQUQGZ5rIwA0K6WuAbmgHanmbYDKM0aZA5gK4ZQAmcAL5w8UCCDgByNASJsoUgFBLg9NFDwZkaOAEkAYsAA22KAGdESuKOAWYALjjmYUNZ2vOiEWvycu3Wg8hFTUzLR19ACU0c0haczQAESwMKxt+VP9XdyUQpWQfF0ZKA20FAE84AF44AAoAShqAPnSUIvgkDDAwYwqjUw1zLjQYFJgMAwAPYRqS7AAJDF9jIcaVG0KE+AASTIm51CY0VnYAHj0YuKLk1Oa6pH2MJykpYQaN9u24HbwTM0stSOlFO6AuAwB9wQnhsf3sLykJBhXi2fmkyhsQg+ni2xR2AAsMOYAGoYYzAfgQoZzX7-IYAOhA3Tqf0GFhacAA8gAjABW8npVDJ3FiLLpFga9LQNCgFTqACEIBBVssGtibDw+PwHsjkMYIMgANZObq9fri4bI8wQbhQHROWlsy02WHih2EklkilUixIl1wCZQTijJzBsapaaeLGfdAwW20No2PapP0ux0A1NJj2k8mUi2ZuCmvo+50usPjSZTKN5FS4+DAxbLfirdm1Roc6GbDqFnrFi2HCjYHA0ejrHHd8sRmZAwe4OTEcH56KxeKJCv3dVwWPxxM9s0lguTiaRzE1pRoKaQWCIeZoMrEaBVEJAA)

**Comment by igorkamyshev** [comment]
Note for me in future: the problem is usage of `traverseParentByType`.

**Comment by igorkamyshev** [comment]
fixed https://github.com/effector/eslint-plugin/releases/tag/v0.3.1

Thanks to report
