### ISSUE TITLE
Rule: `no-forward`

### ISSUE THREAD

**Issue by Kelin2025** [effector/eslint-plugin#69]
I'd like to ban `forward({ from, to })` operator, and replace it with `sample({ clock, target })` instead  
The reason is that `sample` does the same thing that `forward` does, but it's completely superior in terms of features
I figured out that every time I write `forward` somewhere, after a ~hour I rewrite it to `sample` because *OK now I need to transform my data*
The only problem is that forward has different execution priority rather than sample, so sometimes it might be important

**Comment by igorkamyshev** [comment]
So, I've decided to add this rule to plugin, but do not include it to recommended preset because it can affect program results.
