### ISSUE TITLE
Rule: `no-guard`

### ISSUE THREAD

**Issue by igorkamyshev** [effector/eslint-plugin#83]
In the next release of Effector, `sample` will be able to `filter` signals. Shall we add a rule that suggest replacing `guard`-s by `sample`-s?

**Comment by igorkamyshev** [comment]
@effector/core what do you think, folks?

**Comment by doasync** [comment]
I support this idea. Such a rule would be necessary anyway. New users should be recommended against using guard when sample with filter is released. This rule would be useful during refactoring. Eventually guard will be absorbed by sample and this rule will serve us well in the transition.

**Comment by YanLobat** [comment]
`guard` won't be deprecated until major release anyway, in future - yes, but I would not force that rule too early, we can try it out let's say one month after upcoming minor release later this year

**Comment by egorguscha** [comment]
I agree with @doasync, the new users won't have to make a choice between guard and sample, besides for those who already use it, it can be easier to refactor

**Comment by binjospookie** [comment]
Maybe smth like `ban-operators`?

**Comment by igorkamyshev** [comment]
> Maybe smth like `ban-operators`?

What do you mean?

**Comment by binjospookie** [comment]
A rule that allows you to ban not only the `guard` or `forward`, but all together

**Comment by igorkamyshev** [comment]
Got it, sounds good 👌
