### ISSUE TITLE
Rule `no-duplicate-on`

### ISSUE THREAD

**Issue by alatielle** [effector/eslint-plugin#85]
The linter throws an error
"ESLint: Method `.on` is called on store `undefined` more than once for inputs.changeReturnDate.(effector/no-duplicate-on)"
when .on is applied to a store through an object property (`outputs.$something`). The error goes away when the store containing object is destructured

**Comment by igorkamyshev** [comment]
Thanks for report. It's definitely a bug.

I'm working on #82 PR, so I'll fix it right after that. Fix will be released in 0.6.0.
