### ISSUE TITLE
Add support to the `rule.meta.docs.url` property on the rules

### ISSUE THREAD

**Issue by ainursharaev** [effector/eslint-plugin#98]
Please refer to this [documentation](https://github.com/jfmengels/eslint-rule-documentation/blob/master/contributing.md)

**Comment by igorkamyshev** [comment]
What do you mean? Now, every rule must have this field and there are some tests — https://github.com/effector/eslint-plugin/blob/master/puglin.test.js#L8

**Comment by ainursharaev** [comment]
I'm sorry, it has nothing to do with this plugin.

I'm using [eslint-find-rules](https://github.com/sarbbottam/eslint-find-rules) to check all the rules in my ESLint config, and that package use [eslint-rule-documentation](https://github.com/jfmengels/eslint-rule-documentation) under the hood to get URL to a rule's doc, so I need to address my problem to them.
